### ISSUE TITLE
create URDF rover description file

### ISSUE THREAD

**Issue by bitmorse** [Octanis1/Octanis1-ROS#10]
A URDF file is required which contains a kinematic model of the rover. This file will allow the [robot state publisher](http://wiki.ros.org/robot_state_publisher/Tutorials/Using%20the%20robot%20state%20publisher%20on%20your%20own%20robot) to correctly broadcast the robot state to "tf". 

Tutorials:
- http://wiki.ros.org/urdf/Tutorials/Create%20your%20own%20urdf%20file
- http://www.brazenbot.com/Lab3Kine.pdf

**Comment by jajoe** [comment]
The URDF file is done (I've pushed on the git). I will add the robot state publisher tomorrow.
