### ISSUE TITLE
make a roslaunch file with rosbag record setup, stop recording on HOME waypoint reached

### ISSUE THREAD

**Issue by bitmorse** [Octanis1/Octanis1-ROS#11]
make a central launchfile that starts all required nodes and a rosbag recording. this launchfile should run on boot.

stop recording on HOME waypoint reached

**Comment by traffael** [comment]
SBC will receive a COMMAND_LONG message with command MAV_CMD_COMPONENT_ARM_DISARM 

- to start all required nodes (param1 = 1: ARM)
or
-  to stop recording (param1=0: DISARM)

It needs to confirm this message by sending a  COMMAND_ACK ( #77 ) message back to the mainboard (via mav_UART) to confirm or deny the command

**Comment by bitmorse** [comment]
recording node no longer functions. using built-in mavros functionality instead. record on arm, stop record on disarm. closed.
