### ISSUE TITLE
mavros setup (for GPS fix access)

### ISSUE THREAD

**Issue by bitmorse** [Octanis1/Octanis1-ROS#13]
Use mavros (http://wiki.ros.org/mavros) to publish "~global_position/global (sensor_msgs/NavSatFix)" and add config line to robot_localization launch file. Requires mainboard hardware.

This means running the "mavros_node" node with the "global_position" plugin.

**Comment by traffael** [comment]
works, requires tweaking of config for seamless operation with mainboard
