### ISSUE TITLE
Implement closed loop controller for LIDAR motor

### ISSUE THREAD

**Issue by bitmorse** [Octanis1/Octanis1-ROS#6]
LIDAR will not output data as long as RPM < 180. Power consumption of the spinning motor varies with temperature. Therefore a controller is required that keeps the motor spinning at 180RPM.

Controller software should be implemented on the Olimex A20. For hardware, an I2C PWM driver could be used which should be connected to the Olimex A20 I2C bus and the EPS supply. Alternatively, you can enable the PWM module by [recompiling the kernel](https://www.olimex.com/wiki/How_to_add_pwm). The motor requires 3V at ambient and 6V at -18C. 

More information on the LIDAR is on the wiki: http://wiki.octanis.org/orb/lidar

**Comment by qcabrol** [comment]
ROS installed, xv11 driver not pulling data when the lidar is connected on uart0 (/dev/ttyS0), need to use a USB adapter or review the driver code.

**Comment by bitmorse** [comment]
The lidar has the launchpad which you can use as a usb to uart adapter. The
adapter should appear as ttyACM or ttyAMA with the appropriate index (it
make 2 devices: 0 and 1).

**Comment by bitmorse** [comment]
I2C motor controller set to arrive Monday and can be tested then. Use the I2C bus on UEXT1.
