### ISSUE TITLE
Install Debian on Olimex A20 board, which includes drivers for the A20 SOM.

### ISSUE THREAD

**Issue by bitmorse** [Octanis1/Octanis1-ROS#7]
Install "custom" Debian on Olimex A20 board, which includes drivers for the A20 SOM. Please follow the guides by Olimex as closely as possible as the A20 CPU is very specific and requires the correct drivers to function.
If possible, recompile the kernel with PWM enabled.

An image of the SD card should be made when a good base configuration has been achieved.

Guide: https://olimex.wordpress.com/2013/11/05/building-the-ultimate-debian-sd-card-for-linux-with-kernel-3-4-for-a20-olinuxino-micro/

**Comment by qcabrol** [comment]
Issue solved, tutorial to come soon on the wiki page at http://wiki.octanis.org/orb/olimexa20
